[workspace]
members = ["ngao"]
resolver = "2"

[workspace.package]
authors = ["Rod Conan <rconan@gmto.org>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/rconan/grsim"
categories = ["science", "simulation"]
keywords = ["telescope", "astronomy"]

[workspace.dependencies]
gmt_dos-clients = { version = "2.2.0" }
gmt-fem = { version = "5.0.0" }
gmt-fem-code-builder = { version = "1.0" }
gmt_dos-actors = { version = "7.1.1" }
dos-uid-derive = { version = "2.0.0" }
gmt_dos-clients_io = { version = "2.4.0"}
gmt_dos-clients_fem = { version = "3.0.0"}
gmt_dos-clients_mount = { version = "2"}
gmt_dos-clients_m1-ctrl = { version = "2.0.0" }
gmt_dos-clients_m2-ctrl = { version = "1.1.0"}
gmt_dos-clients_arrow = { version = "1.1.0"}
gmt_dos-clients_domeseeing = { version = "1.1.0" }
gmt_dos-clients_windloads = { version = "2.0.1"}
gmt_dos-clients_crseo = { version = "1.0.1" }
gmt_dos-clients_transceiver = { version = "0.2.0"}
gmt_dos-clients_scope = { version = "0.2.0", default-features = false }
log = "0.4.17"
thiserror = "1.0.36"
tokio-test = "0.4"
nalgebra = "0.32.1"
tokio = { version = "1.25.0" }
anyhow = "1.0.68"
crseo = { version = "0.6.1" }
rayon = "1.6.1"
env_logger = "0.10.0"
matio-rs = "1.3.1"
skyangle = "0.2.2"
nanorand = "0.7.0"
serde = { version = "1.0.160", features = ["derive", "rc"] }
bincode = "2.0.0-rc"
apache-arrow = { version = "30.0", package = "arrow" }
parquet = "30.0"
zip = "0.5.13"
bytes = "1.3.0"
indicatif = { version = "0.17.3" }
tracing = "0.1.37"
flume = "0.10.14"

[profile.release]
lto = "thin"