[workspace]
members = ["open-loop", "ngao", "ngao-opm"]
resolver = "2"

[workspace.package]
authors = ["Rod Conan <rconan@gmto.org>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/rconan/grsim"
categories = ["science", "simulation"]
keywords = ["telescope", "astronomy"]
publish = false

[workspace.dependencies]
anyhow = "1.0.75"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
gmt_dos-actors = "10.2"
gmt_dos-clients = "4.0"
interface = { version = "1.0", package = "gmt_dos-actors-clients_interface" }
gmt_dos-clients_io = "4.1"
gmt_dos-clients_arrow = "2.0"
gmt_dos-clients_crseo = "4.1"
gmt_dos-clients_scope = { version = "3.0", features = ["server"] }
gmt_dos-clients_scope-client = "0.2.1"
crseo = "0.9"

#[profile.release]
#lto = "fat"
