[package]
name = "grsim_open-loop"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
publish = true

[dependencies]
anyhow = "1.0.75"
gmt_dos-actors = "7.1.2"
gmt_dos-clients = "2.2.0"
gmt_dos-clients_arrow = { version = "1.1.0", optional = true }
gmt_dos-clients_crseo = { version = "2.0.1", optional = true }
gmt_dos-clients_io = "2.5.0"
gmt_dos-clients_scope = { version = "0.2.0", path = "../../dos-actors/clients/scope", optional = true }
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }

[features]
default = ["scope-server"]
scope-server = [
    "gmt_dos-clients_arrow",
    "gmt_dos-clients_crseo",
    "gmt_dos-clients_scope/server",
]
scope-client = ["gmt_dos-clients_scope/client"]
