[package]
name = "ltao-tests"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
crseo.workspace = true
gmt_dos-clients = { workspace = true, features = ["gif", "nalgebra"] }
gmt_dos-clients_crseo = { workspace = true, features = ["faer"] }
gmt_dos-clients_io.workspace = true
interface.workspace = true
serde-pickle = "1.1.1"
skyangle = "0.2.2"
geotrans = {git = "https://github.com/rconan/geotrans.git", branch = "main"}
tokio.workspace = true
gmt_dos-actors.workspace = true
gmt_dos-clients_arrow.workspace = true
faer = "0.19.4"
serde = { version = "1.0.214", features = ["derive"] }
