[package]
name = "scopes"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
interface = { version = "0.1", package = "gmt_dos-actors-clients_interface" }
gmt_dos-clients_io = "3.1"
gmt_dos-clients_scope-client = "0.2"
tokio = "1.34.0"


[workspace]
