name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build open-loop
      run: cargo build --verbose --bin open-loop
    - name: Build ngao
      run: cargo build --verbose --bin ngao 
